language: go

notifications:
  email: false

os:
  - linux

after_success:
  - bash <(curl -s https://codecov.io/bash)

go:
  - 1.6

script: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... 
